# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: "Auto Build"
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  auto-build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["corne_left","corne_right", "settings_reset"]'
      alphas: '["QWERTY"]'
      nav: '["vi"]'
      layers: '["default"]'
      mapping: '["default"]'
      custom_config: '["default"]'
      kconfig: '["default"]'
      branches: '["default"]'
      modules: '["default"]'
